# Day_10

In [19]:
f = open("Students.txt","w+")
print(f.tell())
f.write("hii welcome")
print(f.tell())
f.write("\nthis is python traning")
print(f.tell())
data = f.read()
print(data)
print(f.tell())
f.close()

0
11
35

35


# Matplotlib Tutorial

# what is Matplotlib

Matplotlib is a low level graph plotting library in python that serves as a visualization utility.

Matplotlib was created by john D.Hunter

Matplotlib is open source and we can use it freely

Matplotlib is open source and we can use it freely

Matplotlib is mostly written in python a few segments are written in c, Objective-C and javascript for platform compatibility

In [20]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.


In [21]:
import matplotlib

print(matplotlib.__version__)

3.3.4


# PYplot

most of the matplotlib utilities lies under the pyplot submodule and are usually imported under the plt alias:

In [ ]:
import matplotlib.pyplot as plt

# now the pyplot package can be referred to as plt.



# Numpy introduction


## what is Numpy

Numpy is a pyhton library used for working with arrays.

it also has function for working in domain of linear algebra,fourier transform and matrices.

Numpy was created in 2005 by Travis oliphant. It is an open source project and you can use it freely

Numpy stands for numerical python


# Why Use Numpy?

In Python we have lists that serve the purpose of arrays but they are slow to process.


Numpy aims to provide an array object that is up to 50x faster than traditional python lists.


The array object in Numpy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Array are very frequently used in data science, where speed and resource are very important


# why is Numpy Faster than lists?

Numpy arrays are stored at one continuous  place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why Numpy is faster than lists. Also it is optimized to work with latest CPU architectures.




In [22]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy

arr = numpy.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


# Numpy as np

Numpy is usually imported under the np alias.

Create an alias with the as keyword while importing:


In [2]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

print(arr)

[1 2 3 4 5 6]


In [3]:
import numpy as np

print(np.__version__)

1.20.1


# Numpy creating Arrays

## create a Numpy ndarray object

Numpy is used to work with arrays. The arrays object in Numpy is called ndarray.

We can create a Numpy ndarray object by using the array() function.




In [4]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


To create an ndarray, we can pass a list,tuple or any array-like object into the array() method, and it will  be converted into an ndarray:

In [5]:
import numpy as np

arr = np.array((1,2,3,4,5))

print(arr)

[1 2 3 4 5]


# Dimensions in Arrays

A dimension in arrays is one level of array depth(nested arrays).

___nested array___ : are arrays that have arrays as their elements.

# 0-D Arrays

0-D arrays, or Scalars are the elements in an array. Each value in an array is a 0-D array.

In [6]:
import numpy as np

arr = np.array(42)

print(arr)

42


# 1-D Arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

these are the most common and basic arrays.

In [7]:
import numpy as np

arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


# 2-D Arrays 

An array that has 1-D arrays as its elements is called a 2-D array

These are often used to represent matrix or 2nd order tensors.

In [9]:
import numpy as np

arr = np.array([[1,3,6],[2,4,8]])

print(arr)

[[1 3 6]
 [2 4 8]]


# 3-D arrays

An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [12]:
import numpy as np

arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[7,8,9],[0,1,2],[4,5,6]]])

print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[7 8 9]
  [0 1 2]
  [4 5 6]]]


# Check Number of Dimensions?

Numpy Arrays provides the ndim attribute that return an interger that tell us how many dimensions the array have.

In [21]:
import numpy as np

a=np.array(42)
b=np.array([1,2,3,4,5,6])
c=np.array([[1,3,6],[2,4,8]])
d=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[7,8,9],[0,1,2],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Higher Dimensional Arrays

An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument

In [12]:
# Create an array with 6 dimensions and verfiy that it has 5 dimension:

import numpy as np

arr = np.array([1,2,3,4] , ndmin=32)# the maximum number of ndmin allowes is =32

print(arr)

print(" no. of dimensions: ", arr.ndim)

ValueError: ndmin bigger than allowable number of dimensions NPY_MAXDIMS (=32)

# Numpy Indexing Array

# access array elements 

Array indexing is the same as accessing an array element.

you can access an array element by referring to its index number.

The indexes in Numpy arrays start with 0,meaning that the first element has index 0,and the second has index 1 etc.

In [25]:
# accessing the first element from the following array:

import numpy as np

arr = np.array([1,2,3,4,5])

print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])

1
2
3
4


# Access 2-D Arrays

to access elements from 2-D arrays we can use comma separated intergers represting the dimension and the index of the element

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column

In [36]:
import numpy as np

arr = np.array([[1,2,3,4,5,6],[4,5,6,7,8,9,]])

print("1st row 2nd element and 2nd row 1st element: ",arr[0,1] , arr[1,0])
print("1st row 6th element and 2nd row 5th element: ",arr[0,5] , arr[1,4])
print("1st row 5th element and 2nd row 3rd element: ",arr[0,4] , arr[1,2])

1st row 2nd element and 2nd row 1st element:  2 4
1st row 6th element and 2nd row 5th element:  6 8
1st row 5th element and 2nd row 3rd element:  5 6


# 3 - D Arrays 

to element forrm 3-D arryes we cab use comma separated intgers representing the dimensional and the index of the elemnt.

In [40]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0,0,0])
print(arr[0,0,1])
print(arr[0,0,2])
print(arr[0,1,0])
print(arr[0,1,1])
print(arr[0,1,2])
print(arr[1,0,0])
print(arr[1,0,1])
print(arr[1,0,2])
print(arr[1,1,0])
print(arr[1,1,1])
print(arr[1,1,2])

1
2
3
4
5
6
7
8
9
10
11
12


# negativing Indexing

use negative indexing to access an array from the end

In [41]:
# printing the last element of 2nd dim

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print("Last element from 2nd dim: ",arr[1,-1])

Last element from 2nd dim:  10


# NumPy Array Slicing

# Slicing arrays

slicing in python means taking elements from one given index to another given index.

we pass slice instead of index like this[start:end]

we can also define the step like this:[start:end:step]
    
If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

if we don't pass step its considered 1

In [48]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])
# slice elements from index  1 to index 5 from the following array
print(arr[1:5])

[2 3 4 5]


In [45]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
# slice elements form index 4 to the end of the array
print(arr[4:])

[5 6 7 8]


In [46]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9])
# slice element from the begining to index 4(not included):
print(arr[:4])

[1 2 3 4]


# negative silcing

use the minus operator to refer to an index from the end:

In [47]:
# slicing from the index 3 from the end to index 1 from the end:

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])

print(arr[-3:-1])

[6 7]


# Step 

use the step value to determine the step of the slicing:
    
    

In [52]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
# Return every other element from
print(arr[1:5:2])
print(arr[1:5:3])
print(arr[0:8:6])

[2 4]
[2 5]
[1 7]


In [55]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])

print(arr[::2])
print(arr[::4])
print(arr[::3])

[1 3 5 7]
[1 5]
[1 4 7]


In [57]:
# Slicing 2-D arrays

import numpy as np

arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

print(arr[0,2:5])
print(arr[1,3:])

[3 4 5]
[10 11 12]


In [60]:
# from both elements return index 2:

import numpy as np

arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

print(arr[0:2,2])

# return index number 5
print(arr[0:5 ,5])

[3 9]
[ 6 12]


In [63]:
# from both element slice index 1 to index4 this will return a 2-d array

import numpy as np

arr =np.array([[1,2,3,4,5,6,7,],[8,9,10,11,12,13,14]])

print(arr[0:2,1:4])
print(arr[0:5,1:6])

[[ 2  3  4]
 [ 9 10 11]]
[[ 2  3  4  5  6]
 [ 9 10 11 12 13]]


In [64]:
# accessing 3-d element
import numpy as np


arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0:0:1,0:1:1])

[]


# Numpy Data Types 

# Data Types in python

By default pyhton have these data types:
    
___Strings___ - Used to represent text data, the text is given under quote marks. e.g. "ABCD"

___integer___ - Used to represent integer numbers. e.g. -1,-2,-3

___float___ - used to represent real numbers. eg. 1.2,42.42

___boolean___ - used to represent True or False.

___complex___ - used to represent complex numbers. eg.1.0 + 2.0j, 1.5 +2.5j


# Data Types in Numpy

Numpy has some extra data types, and refer to data types with one character, like i for intergers u for unsigned intergers etc.

Below is a list of all data types in numpy and the characters used to represent them.

___i___ - integer.

___b___ - boolean

___u___ - unsigned integer

___f___ - float

___c___ - complex float

___m___ - timedate

___M___ - datetime

___O___ - object

___S___ - String

___U___ - unicode string

___V___ - fixed chunk of memory for other type(void)

# Checking the Data type of an Array

The Numpy array object has a property called dtype that returns the data type of the array:

In [70]:
# get the datatype of an array object:

import numpy  as  np

arr = np.array([1,2,3,4])

print(arr.dtype)

# the datatype array containing strings:

import numpy as np

a = np.array(['apple', 'banana', 'cherry'])

print(a.dtype)


int32
<U6


# Creating Arrays With a Defined Data Type

WE use the array() fucntion to create arrays, this function can take an optional argument: dtype that allows us to defined the expected data type of the array elements

In [77]:
import numpy as np

a = np.array([1,2,3,4,5] ,dtype='i')# S5 is defind size of the string


print(a.dtype)

int32


In [13]:
import numpy as np

a = np.array([1,2,3,4,5] ,dtype='S')# S5 is defind size of the string


print(a)

[b'1' b'2' b'3' b'4' b'5']


In [79]:
import numpy as np

a = np.array([1,2,3,4,5] ,dtype='f')# S5 is defind size of the string

print(a)
print(a.dtype)

[1. 2. 3. 4. 5.]
float32


# What if a value can not be converted?

If a type is given in which elements can't be casted then Numpy will raise a valueError

In [84]:
import numpy as np

#arr = np.array(["a","b","c"] dtype='i')

#print(arr)
#print(arr.dtype)

# Converting Data Type on Existing Arrays

The best way to change the data type of an existing array, is to make a copy of the array with the astype()

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using  a string like 'f' for float 'i' for integer etc. or you can use the data type directly like float for float and int for integer

In [93]:
import numpy as np

arr = np.array([1.1,2.1,3.1])


narr = arr.astype('int')
print(arr.dtype)
print(narr)
print(narr.dtype)

float64
[1 2 3]
int32


In [94]:
import numpy as np

arr = np.array([1, 0, 7])

newarr = arr.astype(float)

print(newarr)
print(newarr.dtype)


[1. 0. 7.]
float64


In [95]:
import numpy as np

arr = np.array([1, 0, 3,4,7])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)


[ True False  True  True  True]
bool


# NumPy Array Copy vs View

# The difference Between copy and view

the main difference between a copy and a view of an array is that the copy is a new array and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view

# Copy

In [100]:
# Make a copy and make change in original array,and display both arrays:

import numpy as np

x = np.array([1,2,3,4,5,6,7])
y = x.copy()
x[1] = 200
print("Original array: ",x)
print("Copy of original array: ",y)

#copy should not affect by the changes made to the original array.

Original array:  [  1 200   3   4   5   6   7]
Copy of original array:  [1 2 3 4 5 6 7]


In [101]:
import numpy as np

m = np.array(["Elango","Rohith","Harish","Sheyam"])
n = m.copy()
m[1] = "Mani"
print(m)
print(n)

['Elango' 'Mani' 'Harish' 'Sheyam']
['Elango' 'Rohith' 'Harish' 'Sheyam']


# View 

In [102]:
# Make a view change the original array, and display both arrays:

import numpy as np

x = np.array([1,2,3,4,56,])
y = x.view()
x[4] = 5
print(x)
print(y)

# the view should be affected by the changes made to the original array.

[1 2 3 4 5]
[1 2 3 4 5]


# Check if Array Owns its Data 

As mentioned above,copies owns the data and views does not own the data,but how can we check this?

Every Numpy array has the attributes base that returns None if the array owns the data.

Otherwise, the base attribute refers to the original object.

In [103]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

#copy returns none
#views returns the original array

None
[1 2 3 4 5]


In [107]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

x=arr.copy()
y=arr.view()
arr[5]=7

print(x.base)
print(y.base)

None
[1 2 3 4 5 7]


# Numpy Arrays Shape

# Shape of an Array

the shape of an array is the number of element in each dimension.

# Get the shape of an Array

Numpy arrays have an attribute called shape that return a tuple with each index having number of corresponding elements.



In [108]:
import numpy as np

arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8]])

print(arr.shape)


(2, 4)


In [14]:
import numpy as np

arr = np.array([[[1, 2, 3, 4], [5, 6, 7, 8],[9,10,11,12]]])

print(arr.shape)
print(arr)


(1, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [110]:
# Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4, and verify that last dimension has 2 elements and the second has 4

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


# What does the shape tuple represent?

Integers at every index tells about the number of elements tha corresponding has.

In the example above at index-4 we have value  4 so we can say that 5th (4+1 th)dimension has 4 elements.

# Numpy array reshaping

# Reshaping arrays 

Reshaping means changing the shape of an array

The shape of an array is the number of elements in each dimension

By reshaping we can add or remove dimensions or change number of elements in each dimension.

# reshape from 1-D to 2-D

In [121]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

x = arr.reshape(3,4)
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
# Reshape from 1-D to 3-D

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])

x = arr.reshape(2,4,3)

print(x)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]
